### ISSUE TITLE
Need help, cant switch weapons with button***

### ISSUE THREAD

**Issue by BCarr007i** [hippogamesunity/MilitaryHeroesHub#2]
Could you please give a more detailed explanation on how to switch weapons during run time with a button???.....  I keep referring to the online manual and it only says 

Copy SpriteCollection object from our scene to your scene
Let's assume that your script already has assigned properties SpriteCollection and Character (simply make links to the instances of SpriteCollection and Character as public properties of your script)
Refer to ExampleScripts/ChangingEquipment.cs for code examples as well as to Character methods, for example Character.EquipMeleeWeapon 

Desperately need help understanding this?

**Comment by hippogamesunity** [comment]
Hi! Did you check example scripts?

**Comment by BCarr007i** [comment]
Yes I did. But Im not finding how to set it up to attach it to a button during runtime.

**Comment by BCarr007i** [comment]
Stuck for hours.....

**Comment by BCarr007i** [comment]
Ok, I JUST FIGURED IT OUT THROUGH THE EXAMPLE SCRIPTS!!  Disreguard… Thanks!
