### ISSUE TITLE
Scripts cannot be loaded

### ISSUE THREAD

**Issue by BCarr007i** [hippogamesunity/MilitaryHeroesHub#4]
![milHero](https://user-images.githubusercontent.com/30476138/131649624-57bccc9d-8156-449f-837b-809e600a1ba7.jpg)
None of the scripts from the military heroes package are working

**Comment by BCarr007i** [comment]
Do you know what the compilation errors are?  It does this as soon as I import into a new project

**Comment by hippogamesunity** [comment]
They are displayed in Console window.

ср, 1 сент. 2021 г., 20:20 BCarr007i ***@***.***>:
